const GROUND_LAYER = 1

const GUN_ENTITY_Z = 20

const GUN_ENTITY_LAYER = 0
const GUN_ENTITY_MASK = GROUND_LAYER
const GUN_ENTITY_AREA_LAYER = 0
const GUN_ENTITY_AREA_MASK = 16

const BULLET_LAYER = 8
const BULLET_MASK = GROUND_LAYER

const ENEMY_LAYER = 0
const ENEMY_MASK = GROUND_LAYER + BULLET_LAYER
const ENEMY_ATTACK_LAYER = 0
const ENEMY_ATTACK_MASK = 4

const PLAYER_LAYER = ENEMY_ATTACK_MASK + GUN_ENTITY_AREA_MASK
const PLAYER_MASK = GROUND_LAYER