#ifndef GAME_CONST_H
#define GAME_CONST_H
#include <stdint.h>

namespace z_index {
const int64_t GUN_ENTITY_Z = 20;
}

namespace layers {
const int64_t GROUND_LAYER = 1;

const int64_t GRENADE_LAYER = 64;
const int64_t GRENADE_MASK = 0;

const int64_t GUN_ENTITY_LAYER = 0;
const int64_t GUN_ENTITY_MASK = GROUND_LAYER + GRENADE_LAYER;
const int64_t GUN_ENTITY_AREA_LAYER = 16;
const int64_t GUN_ENTITY_AREA_MASK = 0;

const int64_t BULLET_LAYER = 8;
const int64_t BULLET_MASK = GROUND_LAYER;

const int64_t BULLET_SHELL_LAYER = 0;
const int64_t BULLET_SHELL_MASK = GROUND_LAYER + BULLET_SHELL_LAYER;

const int64_t ENEMY_DAMAGE_LAYER = 0;
const int64_t ENEMY_DAMAGE_MASK = BULLET_LAYER + GRENADE_LAYER;

const int64_t ENEMY_LAYER = 32;
const int64_t ENEMY_MASK = GROUND_LAYER;

const int64_t ENEMY_BULLET_LAYER = 4;
const int64_t ENEMY_BULLET_MASK = GROUND_LAYER;

const int64_t PLAYER_LAYER = 128;
const int64_t PLAYER_MASK = GROUND_LAYER + GUN_ENTITY_AREA_LAYER;

const int64_t PLAYER_LETHAL_LAYER = 0;
const int64_t PLAYER_LETHAL_MASK = ENEMY_BULLET_LAYER + GRENADE_LAYER;

const int64_t ENEMY_SEE_MASK = GROUND_LAYER + PLAYER_LAYER;

const int64_t AUDIO_AREA_MASK = 256;
}
#endif
